In [38]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
import tensorflow as tf
import numpy as np

In [39]:
model_name = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [40]:
model = TFAutoModelForSequenceClassification.from_pretrained(model_name)


All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [51]:
text="I am good."

In [52]:
tokenizer(text, return_tensors="tf")

{'input_ids': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[ 101, 1045, 2572, 2204, 1012,  102]])>, 'attention_mask': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1]])>}

In [53]:
input=tokenizer(text, return_tensors="tf")

In [54]:
output=model(**input)

In [55]:
tf.nn.softmax(output.logits, axis=-1).numpy()

array([[1.5690335e-04, 9.9984312e-01]], dtype=float32)

In [56]:
prob=tf.nn.softmax(output.logits, axis=-1).numpy()[0]

In [57]:
prob

array([1.5690335e-04, 9.9984312e-01], dtype=float32)

In [58]:
predicted_class_id = np.argmax(prob)
model.config.id2label[predicted_class_id]

'POSITIVE'